# Generated by Django 5.0 on 2024-02-19 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_rest", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="assigned_contributor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_contributor",
                to="api_rest.contributor",
            ),
        ),
    ]
