# Generated by Django 5.0 on 2024-01-28 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_rest", "0004_alter_issue_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="assigned_to",
            new_name="author",
        ),
    ]
