# Generated by Django 5.0 on 2024-02-01 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_rest", "0009_alter_project_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="contributors",
        ),
    ]
